### ISSUE TITLE
Error on getOverride for jspm:npm

### ISSUE THREAD

**Issue by RyanFDev** [nfl/react-wildcat#151]
I am getting the following error when using make install after cloning your repo:

         warn Error on getOverride for jspm:npm
           Error: Command failed: /bin/sh -c git fetch --all && git reset --hard origin/master
           error: cannot open .git/FETCH_HEAD: Permission denied

             at ChildProcess.exithandler (child_process.js:213:12)
             at emitTwo (events.js:87:13)
             at ChildProcess.emit (events.js:172:7)
             at maybeClose (internal/child_process.js:829:16)
             at Socket.<anonymous> (internal/child_process.js:319:11)
             at emitOne (events.js:77:13)
             at Socket.emit (events.js:169:7)
             at Pipe._onclose (net.js:486:12)

If I do a sudo make install the make file completes it's installation; however the app itself won't run unless I sudo and then I get permission errors on the actual app.

I've used git fetch to create the FETCH_HEAD as I first thought that may be the issue, and made sure I am the proper owner of the file. 

Would love to try out your environment but need some help please!

**Comment by doctyper** [comment]
Hm, it would seem you have permission issues in your environment. Wildcat does not make any assumptions on your privileges and does not require root access.

I would try to reinstall or check permissions on your node modules.

**Comment by jamsea** [comment]
@RyanFDev I'm closing this because there hasn't been much activity. Let me know if you're still stuck.
